---
- name: Set service facts
  set_fact: neutron_plugin_agent="neutron-plugin-openvswitch-agent"
  when: ansible_os_family == 'Debian'

- name: Set service facts
  set_fact: neutron_plugin_agent='neutron-openvswitch-agent'
  when: ansible_os_family == 'RedHat'
